---
name: Skolmaten School Menu
version: 0.1.0
slug: skolmaten_menu
description: "Fetches school lunch menus from Skolmaten.se and exposes them as Home Assistant sensors"
url: https://github.com/your-username/skolmaten-hass-addon
init: false
arch:
  - aarch64
  - amd64
  - armv7
homeassistant_api: true
hassio_api: true
options:
  schools:
    - name: "Östra Real"
      slug: "ostra-real"
  update_interval: 7200
  n_weeks: 2
schema:
  schools:
    - name: str
      slug: str
  update_interval: int(60,259200)  # 1 minute to 3 days
  n_weeks: int(1,10)